<?php

$trickTypes = [
    "T01_EnchantedButterflies",
    "T02_RabbitFromTheTopHat",
    "T03_PubInABottle",
    "T04_CardManipulation",
    "T05_SelfDecapitation",
    "T06_PaperShred",
    "T07_ShatteredMirror",
    "T08_FishingInTheAir",
    "T09_Mutilation",
    "T10_StairsOfWater",
    "T11_BeastWithin",
    "T12_VanishingElephant",

    "T13_MindReading",
    "T14_BreathOfLife",
    "T16_WindowToTheOtherworld",
    "T17_FloatingTable",
    "T18_FutureSight",
    "T19_PeppersGhost",
    "T20_GhostTrap",
    "T21_BalsamosSkull",
    "T22_Séance",
    "T23_SkeletonDance",
    "T24_Metamorphosis",

    "T25_BarricadedBarrels",
    "T26_StocksEscape",
    "T27_BurningMummy",
    "T28_WaterTankEscape",
    "T29_PrisonBreak",
    "T30_ZigZagLady",
    "T31_Walled",
    "T32_WolfCage",
    "T33_BuriedAlive",
    "T34_AssistantsRevenge",
    "T35_IronMaiden",
    "T36_TransportedMan",

    "T37_LinkingRings",
    "T38_LivingPiano",
    "T39_ChineseSticks",
    "T40_Levitation",
    "T41_MechanicalHornet",
    "T42_SawingTheAssistantInHalf",
    "T43_VanishingBirdCage",
    "T44_BulletCatch",
    "T45_AztecLady",
    "T46_HorrorSaws",
    "T47_Automaton",
    "T48_Hellhound",
];