export const staticData = {
    assignments: {
        A01_Theater: { boardLocation: 'theater', category: 'permanent', name: 'Theater', targetAction: 'any', abilityText: [] },
        A02_Downtown: {
            boardLocation: 'downtown',
            category: 'permanent',
            name: 'Downtown',
            targetAction: 'any',
            abilityText: [],
        },
        A03_MarketRow: {
            boardLocation: 'market-row',
            category: 'permanent',
            name: 'Market Row',
            targetAction: 'any',
            abilityText: [],
        },
        A04_Workshop: {
            boardLocation: 'workshop',
            category: 'permanent',
            name: 'Workshop',
            targetAction: 'any',
            abilityText: [],
        },
        A05_DarkAlley: {
            boardLocation: 'dark-alley',
            category: 'permanent',
            name: 'Dark Alley',
            targetAction: 'any',
            abilityText: [],
        },
        A06_GuestPerformer: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Guest Performer',
            targetAction: 'set-up-trick',
            abilityText: [
                'You may set up the <trick-marker> even if the Performance card has no free <trick-marker> slots. Place the <trick-marker> on an unused area anywhere on the Performance card. This <trick-marker> is considered part of the Performance.',
            ],
        },
        A07_OrchestralInterlude: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Orchestral Interlude',
            targetAction: 'set-up-trick',
            abilityText: [
                "You receive your Trick's <link> payment for each <trick-marker> connecting to the <trick-marker> you set up (even if the category symbols don't match).",
            ],
        },
        A08_HeadlinerTrick: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Headliner Trick',
            targetAction: 'set-up-trick',
            abilityText: [
                'If you create one or more <link> as you set up the <trick-marker>, you receive the payment for each <link> twice (including <shard>).',
            ],
        },
        A09_NewTwist: {
            boardLocation: 'theater',
            category: 'special',
            name: 'New Twist',
            targetAction: 'set-up-trick',
            abilityText: ['You may set up the same <trick-marker> on the same Performance card for a second time.'],
        },
        A10_BuyingTime: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Buying Time',
            targetAction: 'set-up-trick',
            abilityText: [
                'After setting up the <trick-marker>, you may switch the position of two Performance cards and receive 3 <coin>.',
            ],
        },
        A11_DurableComponents: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Durable Components',
            targetAction: 'perform',
            abilityText: [
                "At the end of the 'Performance' phase, you may return one of your performed <trick-marker> to its Trick card instead of discarding it.",
            ],
        },
        A12_ArrangedFiasco: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Arranged Fiasco',
            targetAction: 'perform',
            abilityText: [
                'When you <perform>, you receive +1 <fame> for each of your own <trick-marker>, while other players receive -1 <fame> for each of their <trick-marker>.',
            ],
        },
        A13_GrandPremiere: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Grand Premiere',
            targetAction: 'perform',
            abilityText: [
                "If one of your own <trick-marker> in your Performance is performed for the first time in the game, double that Trick's <coin>, <fame>, or <shard> Yield for this Performance (choose one).",
            ],
        },
        A14_StreetPerformance: {
            boardLocation: 'theater',
            category: 'special',
            name: 'Street Performance',
            targetAction: 'reschedule',
            abilityText: [
                "Instead of moving the <trick-marker>, you may remove it from the Performance card and immediately receive that Trick's Yields. Yield modifiers apply.",
            ],
        },
        A15_DirectorsFavor: {
            boardLocation: 'theater',
            category: 'special',
            name: "Director's Favor",
            targetAction: 'reschedule',
            abilityText: ["Instead of moving your own <trick-marker>, you may move an opponent's <trick-marker>."],
        },
        A16_TrickTweaking: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Trick Tweaking',
            targetAction: 'prepare',
            abilityText: ['You receive +1 <trick-marker> on the prepared Trick.'],
        },
        A17_TestRun: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Test Run',
            targetAction: 'prepare',
            abilityText: [
                "You may choose to receive 1 less <trick-marker> on the prepared Trick. If you do, you immediately receive the Trick's <fame>, <coin> and <shard> Yields.",
            ],
        },
        A18_ReplacableParts: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Replacable Parts',
            targetAction: 'prepare',
            abilityText: [
                "You may choose to receive 1 less <trick-marker> on the prepared Trick. If you do, you may put one <trick-marker> on another Trick you own with the same or lower <fame-threshold> (even if you don't meet its <component> requirements).",
            ],
        },
        A19_Invention: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Invention',
            targetAction: 'prepare',
            abilityText: [
                'You receive <fame> equal to the total number of Advanced and Superior <component> required for the prepared Trick.',
            ],
        },
        A20_Ingenuity: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Ingenuity',
            targetAction: 'prepare',
            abilityText: [
                "You may 'Prepare' the Trick even if you don't have enough of one <component> type required for it. You only get 1 <trick-marker> if you 'Prepare' a Trick this way.",
            ],
        },
        A21_UnstablePrototype: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Unstable Prototype',
            targetAction: 'prepare',
            abilityText: [
                'You may return up to 3 <component> required for the prepared Trick to the supply. If you do, you receive:',
                '<bullet> +1 <trick-marker> on the Trick.',
                '<bullet> 1 <fame> and 1 <coin> for each <component> returned.',
            ],
        },
        A22_EnhanceTrick: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Enhance Trick',
            targetAction: 'prepare',
            abilityText: [
                "You may place one of your <shard> on the prepared Trick. It is considered spent. That Trick's <fame> and <coin> Yields are increased by 1 for the remainder of the game.",
            ],
        },
        A23_OnStagePreparation: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'On-stage Preparation',
            targetAction: 'prepare',
            abilityText: [
                "After preparing the Trick, you may immediately move one of the received <trick-marker> onto an empty slot on one of the Performance cards. You don't receive <link> payment if you created a <link> this way.",
            ],
        },
        A24_HiddenTalent: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Hidden Talent',
            targetAction: 'prepare',
            abilityText: [
                "If you used an Apprentice to 'Prepare' the Trick, you may return it to the supply during the 'Return Characters' phase and immediately hire a Specialist. You have to pay Wages for that Specialist this turn.",
            ],
        },
        A25_Freelancer: {
            boardLocation: 'workshop',
            category: 'special',
            name: 'Freelancer',
            targetAction: 'any',
            abilityText: ['You may choose to place this <disk> on any other Location instead of the Workshop.'],
        },
        A26_MassRecruitment: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Mass Recruitment',
            targetAction: 'hire-character',
            abilityText: [
                'If you hire an Apprentice, you may pay 3 <coin> to hire a second one. This costs no additional <action-point> and is independent from the die rolls.',
            ],
        },
        A27_HypnoticMotivation: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Hypnotic Motivation',
            targetAction: 'hire-character',
            abilityText: [
                "You immediately receive the hired <disk>. You may place an Assignment card from your hand below it and place it during this 'Place Characters' phase.",
            ],
        },
        A28_Headhunter: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Headhunter',
            targetAction: 'hire-character',
            abilityText: [
                "You may hire any kind of <disk> regardless of the die roll (as long as it's not an X).",
                "This 'Hire Character' Action costs you 1 less <action-point>.",
            ],
        },
        A29_TrickOverhaul: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Trick Overhaul',
            targetAction: 'learn-trick',
            abilityText: [
                "As you learn this Trick, you may choose to return another Trick to the Dahlgaard Residence. If you do, place all <trick-marker> and the Symbol Marker from the returned Trick on the new Trick. You can only do this if you meet the new Trick's <component> requirements.",
            ],
        },
        A30_ThirstForKnowledge: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Thirst for Knowledge',
            targetAction: 'learn-trick',
            abilityText: [
                "You may learn a Trick from any category regardless of the die roll (as long as it's not an X).",
                "This 'Learn Trick' Action costs you 1 less <action-point>.",
            ],
        },
        A31_LeakedBlueprints: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Leaked Blueprints',
            targetAction: 'learn-trick',
            abilityText: [
                "If the learned Trick has <fame-threshold> 16 or less, you receive it with 1 <trick-marker>, even if you don't meet its <component> requirements.",
            ],
        },
        A32_Investments: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Investments',
            targetAction: 'take-coins',
            abilityText: [
                'You may immediately spend any amount of the received <coin> to buy up to three <component> available at the Market Row.',
            ],
        },
        A33_FameAndFortune: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Fame and Fortune',
            targetAction: 'take-coins',
            abilityText: ['You also gain <fame> equal to the amount of <coin> on the chosen die minus 1.'],
        },
        A34_Interest: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Interest',
            targetAction: 'take-coins',
            abilityText: [
                'After choosing a Bank die, roll it once before setting it to X. Add the rolled amount from the supply to the <coin> you take.',
                "This 'Take Coins' Action costs you 1 less <action-point>.",
            ],
        },
        A35_Empower: {
            boardLocation: 'downtown',
            category: 'special',
            name: 'Empower',
            targetAction: 'any',
            abilityText: [
                "If you use 'Enhance Character' by paying a <shard> when you place this <disk>, you receive 3 additional <action-point> instead of the usual 1.",
            ],
        },
        A36_ComponentSale: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Component Sale',
            targetAction: 'buy',
            abilityText: [
                "As one 'Buy' Action, you may buy up to 4 <component> available at the Market Row, in any combination.",
            ],
        },
        A37_SmuggledGoods: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Smuggled Goods',
            targetAction: 'buy',
            abilityText: [
                'You may lose <fame> equal to the total <coin> price of the bought <component> minus 1 instead of paying <coin> for them.',
            ],
        },
        A38_BarterWithPower: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Barter with Power',
            targetAction: 'buy',
            abilityText: [
                "As one 'Buy' Action, you may return a <shard> to the supply and receive any number of <component> available at the Market Row for a total <coin> value of 4 or less without paying any <coin>.",
            ],
        },
        A39_WorkshopExhibition: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Workshop Exhibition',
            targetAction: 'buy',
            abilityText: ["You receive <fame> equal to the amount of <coin> you paid for this 'Buy' Action minus 1."],
        },
        A40_Shoplifting: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Shoplifting',
            targetAction: 'buy',
            abilityText: [
                "You may take one of the bought <component> directly from the Market Row instead of the supply, without paying its <coin> price. The <component> is removed from the Market Row's stock and replaced with a Basic <component> of your choice.",
            ],
        },
        A41_Logistics: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Logistics',
            targetAction: 'order',
            abilityText: [
                "Place the ordered <component> next to the Market Row's Buy area instead of the Order area. It counts as part of the Market Row's stock this turn. Return this <component> to the supply during the 'Orders Arrive' phase.",
            ],
        },
        A42_TravelingMerchants: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Traveling Merchants',
            targetAction: 'order',
            abilityText: [
                'You may pay the <coin> price plus 1 of the ordered <component> to immediately receive one from the supply.',
                "You may use this for any number of 'Order' Actions.",
            ],
        },
        A43_DubiousSources: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Dubious Sources',
            targetAction: 'quick-order',
            abilityText: [
                "During the 'End Turn' phase, put the <component> on the Quick Order slot into your Workshop instead of returning it to the supply.",
            ],
        },
        A44_BusinessShare: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Business Share',
            targetAction: 'any',
            abilityText: [
                'Whenever an opponent spends <coin> at the Market Row this turn after you placed this <disk>, those <coin> are paid to you.',
            ],
        },
        A45_WorkshopDelivery: {
            boardLocation: 'market-row',
            category: 'special',
            name: 'Workshop Delivery',
            targetAction: 'buy',
            abilityText: [
                "For this 'Buy' Action, <component> types you have in your Workshop count as part of the Market Row's stock and their <coin> price is reduced by 1.",
            ],
        },
    },
    magicians: {
        M01_MasterOfChains: {
            favoriteTrickCategory: 'escape',
            name: 'Master of Chains',
            ability: {
                name: 'Break Free',
                effect: "Before the 'Performance' phase, you may take a special 'Reschedule' Action without placing any Characters. Unlike the normal 'Reschedule' Action, you receive the Link bonuses if you create Link(s) with this placement.",
            },
        },
        M02_TheGreatOptico: {
            favoriteTrickCategory: 'optical',
            name: 'The Great Optico',
            ability: {
                name: 'Mimesis',
                effect: "Once per turn, you may use one of your Permanent Assignment cards with an effect of an opponent's revealed Special Assignment card of the same Location. You may use either the copied card's printed ability or gain its +1 Action Point bonus instead.",
            },
        },
        M03_PriestessOfMysticism: {
            favoriteTrickCategory: 'spiritual',
            name: 'Priestess of Mysticism',
            ability: {
                name: 'Fate Weaving',
                effect: 'For 1 Dark Alley Action Point, you may discard the Active Prophecy, then replace it with any of the Pending Prophecies and draw a new one in its place.',
            },
        },
        M04_TheMechaniker: {
            favoriteTrickCategory: 'mechanical',
            name: 'The Mechaniker',
            ability: {
                name: 'Mechanical Enhancement',
                effect: 'Once per turn, one of your Apprentices receives an additional Action Point when placed at any Location except for the Theater.',
            },
        },
        M05_TheRedLotus: {
            favoriteTrickCategory: 'escape',
            name: 'The Red Lotus',
            ability: {
                name: 'Trick Steal',
                effect: "You may choose to receive the Yield of an opponent's Trick in the same Performance instead of your own Trick's Yield, as long as you are the Performer and the opponent's Trick has the same or lower Fame Threshold as yours. The opponent receives one less Fame for the Trick stolen this way.",
            },
        },
        M06_TheGentleman: {
            favoriteTrickCategory: 'optical',
            name: 'The Gentleman',
            ability: {
                name: 'Magic for the Masses',
                effect: 'Whenever the Magician is placed on a Downtown, Market Row or Dark Alley slot, you receive Fame equal to the number of Trick cards you have.',
            },
        },
        M07_YorubaSpiritmaster: {
            favoriteTrickCategory: 'spiritual',
            name: 'Yoruba Spiritmaster',
            ability: {
                name: 'Soul Possession',
                effect: "Once per turn, before an opponent chooses a card to Perform, you may pay one Shard. If you do, you may choose the card to Perform for that player. The chosen card must have at least one of the opponent's Trick markers on it.",
            },
        },
        M08_Electra: {
            favoriteTrickCategory: 'mechanical',
            name: 'Electra',
            ability: {
                name: 'Supercharge',
                effect: 'You may choose to pile two markers of the same Trick on a Trick slot when you set up a Trick. It counts as one Trick and Link bonuses are paid only once. When performed, this Trick Yields 1/2/3 additional Fame point(s) and Coin(s) depending on its Level (1/2/3).',
            },
        },
    },
    performances: {
        P01_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: true }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 0, coins: 0, shards: 1 },
        },
        P02_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: true },
                    ],
                },
                1.1: { x: 1, y: 1, links: [{ direction: 'left', shard: true }] },
            },
            bonus: { fame: 1, coins: 1, shards: 0 },
        },
        P03_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: true },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'up', shard: true }] },
            },
            bonus: { fame: 1, coins: 0, shards: 0 },
        },
        P04_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'right', shard: true }] },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 1, coins: 0, shards: 0 },
        },
        P05_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'down', shard: false }] },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.2: {
                    x: 1,
                    y: 2,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'left', shard: true },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'right', shard: true }] },
            },
            bonus: { fame: 1, coins: 0, shards: 0 },
        },
        P06_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: true },
                    ],
                },
                0.2: {
                    x: 0,
                    y: 2,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'right', shard: false },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'left', shard: false }] },
            },
            bonus: { fame: 0, coins: 1, shards: 0 },
        },
        P07_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'left', shard: false }] },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'right', shard: false },
                        { direction: 'down', shard: true },
                    ],
                },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 0, coins: 1, shards: 0 },
        },
        P08_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: false },
                        { direction: 'right', shard: true },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: false }] },
                1.1: { x: 1, y: 1, links: [{ direction: 'left', shard: true }] },
            },
            bonus: { fame: 1, coins: 1, shards: 0 },
        },
        P09_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'down', shard: true }] },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'left', shard: false },
                    ],
                },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'right', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 0, coins: 1, shards: 0 },
        },
        P10_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'right', shard: false }] },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: true },
                    ],
                },
                1.1: { x: 1, y: 1, links: [{ direction: 'up', shard: true }] },
            },
            bonus: { fame: 2, coins: 0, shards: 0 },
        },
        P11_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'left', shard: true }] },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'right', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                0.1: { x: 0, y: 1, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 0, coins: 2, shards: 0 },
        },
        P12_RiversideTheater: {
            name: 'Riverside Theater',
            theater: 'riverside_theater',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'down', shard: true }] },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'left', shard: false },
                    ],
                },
                0.1: { x: 0, y: 1, links: [{ direction: 'right', shard: false }] },
            },
            bonus: { fame: 0, coins: 0, shards: 1 },
        },
        P13_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'right', shard: false }] },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'left', shard: true },
                    ],
                },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'right', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 2, coins: 0, shards: 0 },
        },
        P14_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: true }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'down', shard: true },
                        { direction: 'up', shard: false },
                    ],
                },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'down', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.1: { x: 1, y: 1, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 2, coins: 0, shards: 0 },
        },
        P15_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: true }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'right', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.2: {
                    x: 1,
                    y: 2,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'left', shard: false },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'right', shard: false }] },
            },
            bonus: { fame: 0, coins: 3, shards: 0 },
        },
        P16_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: true }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                0.2: {
                    x: 0,
                    y: 2,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                1.2: {
                    x: 1,
                    y: 2,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'up', shard: false },
                    ],
                },
                1.1: { x: 1, y: 1, links: [{ direction: 'down', shard: false }] },
            },
            bonus: { fame: 0, coins: 3, shards: 0 },
        },
        P17_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'left', shard: true }] },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'right', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                1.1: { x: 1, y: 1, links: [{ direction: 'left', shard: false }] },
            },
            bonus: { fame: 2, coins: 1, shards: 0 },
        },
        P18_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'right', shard: false }] },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'left', shard: true },
                    ],
                },
                0.1: { x: 0, y: 1, links: [{ direction: 'right', shard: true }] },
            },
            bonus: { fame: 2, coins: 1, shards: 0 },
        },
        P19_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'down', shard: true }] },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'down', shard: false },
                        { direction: 'left', shard: false },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'up', shard: false }] },
                0.1: { x: 0, y: 1, links: [{ direction: 'right', shard: false }] },
            },
            bonus: { fame: 1, coins: 0, shards: 1 },
        },
        P20_GrandMagorian: {
            name: 'Grand Magorian',
            theater: 'grand_magorian',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: false },
                        { direction: 'right', shard: true },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: false }] },
                1.1: { x: 1, y: 1, links: [{ direction: 'left', shard: true }] },
            },
            bonus: { fame: 3, coins: 0, shards: 0 },
        },
        P21_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'right', shard: false }] },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: true },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'left', shard: false },
                    ],
                },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'right', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                0.2: {
                    x: 0,
                    y: 2,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'left', shard: false }] },
            },
            bonus: { fame: 3, coins: 0, shards: 0 },
        },
        P22_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'left', shard: false }] },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'right', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.2: {
                    x: 1,
                    y: 2,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'left', shard: true },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'right', shard: true }] },
            },
            bonus: { fame: 3, coins: 0, shards: 0 },
        },
        P23_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                0.2: {
                    x: 0,
                    y: 2,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                1.2: {
                    x: 1,
                    y: 2,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'up', shard: true },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'down', shard: true },
                        { direction: 'up', shard: false },
                    ],
                },
                '1.0': { x: 1, y: 0, links: [{ direction: 'down', shard: false }] },
            },
            bonus: { fame: 0, coins: 5, shards: 0 },
        },
        P24_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'down', shard: false },
                        { direction: 'up', shard: true },
                    ],
                },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'down', shard: true },
                        { direction: 'right', shard: false },
                    ],
                },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 0, coins: 5, shards: 0 },
        },
        P25_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                0.2: { x: 0, y: 2, links: [{ direction: 'up', shard: true }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'down', shard: true },
                        { direction: 'up', shard: false },
                    ],
                },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'down', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                '1.0': {
                    x: 1,
                    y: 0,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.1: { x: 1, y: 1, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 2, coins: 2, shards: 0 },
        },
        P26_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'left', shard: true }] },
                '0.0': {
                    x: 0,
                    y: 0,
                    links: [
                        { direction: 'right', shard: true },
                        { direction: 'down', shard: false },
                    ],
                },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'right', shard: false },
                    ],
                },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'left', shard: false },
                        { direction: 'down', shard: false },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'up', shard: false }] },
            },
            bonus: { fame: 2, coins: 0, shards: 1 },
        },
        P27_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                '1.0': { x: 1, y: 0, links: [{ direction: 'down', shard: false }] },
                1.1: {
                    x: 1,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: false },
                        { direction: 'left', shard: true },
                    ],
                },
                1.2: {
                    x: 1,
                    y: 2,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'left', shard: false },
                    ],
                },
                0.2: { x: 0, y: 2, links: [{ direction: 'right', shard: false }] },
                0.1: { x: 0, y: 1, links: [{ direction: 'right', shard: true }] },
            },
            bonus: { fame: 4, coins: 0, shards: 0 },
        },
        P28_MagnusPantheon: {
            name: 'The Magnus Pantheon',
            theater: 'magnus_pantheon',
            slots: {
                '0.0': { x: 0, y: 0, links: [{ direction: 'down', shard: false }] },
                0.1: {
                    x: 0,
                    y: 1,
                    links: [
                        { direction: 'up', shard: false },
                        { direction: 'down', shard: true },
                        { direction: 'right', shard: false },
                    ],
                },
                0.2: {
                    x: 0,
                    y: 2,
                    links: [
                        { direction: 'up', shard: true },
                        { direction: 'right', shard: false },
                    ],
                },
                1.2: { x: 1, y: 2, links: [{ direction: 'left', shard: false }] },
                1.1: { x: 1, y: 1, links: [{ direction: 'left', shard: false }] },
            },
            bonus: { fame: 0, coins: 0, shards: 2 },
        },
    },
    prophecies: {
        P01_Prophecy: { ability: ['Each Character has only 1 base Action Point.'] },
        P02_Prophecy: { ability: ['Any time you receive one or more Shards, you receive an additional one.'] },
        P03_Prophecy: { ability: ['Any time you receive one or more Shards, you also receive 2 Fame.'] },
        P04_Prophecy: { ability: ["Component types in the Market Row's Order area can be bought with 'Buy' Actions."] },
        P05_Prophecy: { ability: ["The 'Draw Further Cards' Action costs 1 Action Point."] },
        P06_Prophecy: { ability: ['All Performer Bonuses are doubled this turn.'] },
        P07_Prophecy: { ability: ["Double the amount of Coins on the chosen die when you take the 'Take Coins' Action."] },
        P08_Prophecy: { ability: ["You receive 2 Action Points instead of 1 when you use 'Enhance Character'."] },
        P09_Prophecy: { ability: ["You may place two Characters on each of your turns during the 'Place Characters' phase."] },
        P10_Prophecy: { ability: ['You immediately receive 2 Fame when you set up an Escape Trick.'] },
        P11_Prophecy: { ability: ['Friday has a Yield modifier: -1 Fame and -1 Coin (similar to Thursday).'] },
        P12_Prophecy: { ability: ["The 'Learn Trick' Action costs 1 Action Point."] },
        P13_Prophecy: { ability: ['You immediately receive 2 Fame when you set up a Mechanical Trick.'] },
        P14_Prophecy: { ability: ["During the 'Performance' phase, all Coin Yields are received as Fame."] },
        P15_Prophecy: { ability: ['If you Advertised this turn, your Apprentices gain +1 base Action Point.'] },
        P16_Prophecy: { ability: ['Thursday and Sunday have no Yield modifiers.'] },
        P17_Prophecy: { ability: ['You immediately receive 2 Fame when you set up an Optical Trick.'] },
        P18_Prophecy: {
            ability: ['You have to pay 3 Coins to use the +2 Action Point Slots at the Downtown, Market Row and Dark Alley.'],
        },
        P19_Prophecy: {
            ability: [
                "During the 'Performance' phase, the performing player's Yield modifier applies to all other players in the Performance (instead of their own).",
            ],
        },
        P20_Prophecy: {
            ability: [
                "Assignment cards are not revealed after the 'Assignment' phase. Players reveal them one by one right before placing the Character above them.",
            ],
        },
        P21_Prophecy: { ability: ['All Components cost 2 Coins when you buy them.'] },
        P22_Prophecy: { ability: ['Saturday has a Yield modifier: +1 Fame and +1 Coin (similar to Sunday).'] },
        P23_Prophecy: { ability: ['You immediately receive 2 Fame when you set up a Spiritual Trick.'] },
        P24_Prophecy: { ability: ["The 'Take Coins' Action costs 1 Action Point."] },
        P25_Prophecy: { ability: ["The 'Hire Character' Action costs 1 Action Point."] },
        P26_Prophecy: { ability: ["You may use 'Enhance Character' in the Theater."] },
        P27_Prophecy: {
            ability: ['You must place your Characters on the Slot with the lowest available Action Point modifier.'],
        },
    },
    tricks: {
        T01_EnchantedButterflies: {
            category: 'optical',
            name: 'Enchanted Butterflies',
            componentRequirements: ['fabric', 'fabric'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 2, coins: 0, shards: 0 },
        },
        T02_RabbitFromTheTopHat: {
            category: 'optical',
            name: 'Rabbit from the Top Hat',
            componentRequirements: ['animal', 'fabric', 'metal'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 3, coins: 1, shards: 0 },
        },
        T03_PubInABottle: {
            category: 'optical',
            name: 'Pub-In-A-Bottle',
            componentRequirements: ['rope', 'saw', 'glass', 'glass', 'glass'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 2, coins: 2, shards: 0 },
        },
        T04_CardManipulation: {
            category: 'optical',
            name: 'Card Manipulation',
            componentRequirements: ['wood', 'wood', 'wood', 'fabric', 'fabric', 'fabric'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 1, coins: 1, shards: 1 },
        },
        T05_SelfDecapitation: {
            category: 'optical',
            name: 'Self Decapitation',
            componentRequirements: ['disguise', 'saw', 'metal', 'metal', 'metal'],
            preparationCost: 1,
            slots: 3,
            level: 2,
            yields: { fame: 3, coins: 2, shards: 0 },
        },
        T06_PaperShred: {
            category: 'optical',
            name: 'Paper Shred',
            componentRequirements: ['mirror', 'saw', 'saw', 'metal', 'metal', 'metal'],
            preparationCost: 2,
            slots: 2,
            level: 2,
            yields: { fame: 4, coins: 2, shards: 1 },
        },
        T07_ShatteredMirror: {
            category: 'optical',
            name: 'Shattered Mirror',
            componentRequirements: ['mirror', 'mirror', 'wood', 'wood', 'wood', 'glass', 'glass', 'glass'],
            preparationCost: 2,
            slots: 2,
            level: 2,
            yields: { fame: 5, coins: 3, shards: 0 },
        },
        T08_FishingInTheAir: {
            category: 'optical',
            name: 'Fishing in the Air',
            componentRequirements: ['rope', 'rope', 'animal', 'animal', 'animal', 'wood', 'wood', 'wood'],
            preparationCost: 2,
            slots: 3,
            level: 2,
            yields: { fame: 3, coins: 4, shards: 1 },
        },
        T09_Mutilation: {
            category: 'optical',
            name: 'Mutilation',
            componentRequirements: ['disguise', 'saw', 'saw', 'mirror', 'mirror', 'fabric', 'fabric', 'fabric'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 6, coins: 5, shards: 0 },
        },
        T10_StairsOfWater: {
            category: 'optical',
            name: 'Stairs of Water',
            componentRequirements: ['mirror', 'cog', 'petroleum', 'petroleum', 'glass', 'glass', 'glass'],
            preparationCost: 3,
            slots: 3,
            level: 3,
            yields: { fame: 5, coins: 4, shards: 2 },
        },
        T11_BeastWithin: {
            category: 'optical',
            name: 'Beast Within',
            componentRequirements: ['disguise', 'mirror', 'animal', 'animal', 'animal', 'fabric', 'fabric', 'fabric'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 7, coins: 3, shards: 1 },
        },
        T12_VanishingElephant: {
            category: 'optical',
            name: 'Vanishing Elephant',
            componentRequirements: ['mirror', 'padlock', 'padlock', 'animal', 'animal', 'glass', 'glass', 'glass'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 9, coins: 4, shards: 0 },
        },
        T13_MindReading: {
            category: 'spiritual',
            name: 'Mind Reading',
            componentRequirements: ['glass', 'glass'],
            preparationCost: 1,
            slots: 3,
            level: 1,
            yields: { fame: 0, coins: 0, shards: 1 },
        },
        T14_BreathOfLife: {
            category: 'spiritual',
            name: 'Breath of Life',
            componentRequirements: ['saw', 'metal', 'fabric', 'fabric'],
            preparationCost: 1,
            slots: 1,
            level: 1,
            yields: { fame: 2, coins: 3, shards: 0 },
        },
        T15_SpiritHand: {
            category: 'spiritual',
            name: 'Spirit Hand',
            componentRequirements: ['animal', 'rope', 'fabric', 'fabric', 'fabric'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 2, coins: 1, shards: 1 },
        },
        T16_WindowToTheOtherworld: {
            category: 'spiritual',
            name: 'Window to the Otherworld',
            componentRequirements: ['mirror', 'petroleum', 'metal', 'metal'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 3, coins: 2, shards: 0 },
        },
        T17_FloatingTable: {
            category: 'spiritual',
            name: 'Floating Table',
            componentRequirements: ['petroleum', 'rope', 'rope', 'rope', 'fabric', 'fabric', 'fabric', 'wood', 'wood', 'wood'],
            preparationCost: 2,
            slots: 2,
            level: 2,
            yields: { fame: 5, coins: 2, shards: 1 },
        },
        T18_FutureSight: {
            category: 'spiritual',
            name: 'Future Sight',
            componentRequirements: ['mirror', 'fabric', 'fabric', 'metal', 'metal'],
            preparationCost: 1,
            slots: 1,
            level: 2,
            yields: { fame: 4, coins: 1, shards: 0 },
        },
        T19_PeppersGhost: {
            category: 'spiritual',
            name: "Pepper's Ghost",
            componentRequirements: ['disguise', 'disguise', 'saw', 'saw', 'glass', 'glass'],
            preparationCost: 2,
            slots: 2,
            level: 2,
            yields: { fame: 4, coins: 5, shards: 0 },
        },
        T20_GhostTrap: {
            category: 'spiritual',
            name: 'Ghost Trap',
            componentRequirements: [
                'animal',
                'animal',
                'animal',
                'fabric',
                'fabric',
                'fabric',
                'glass',
                'glass',
                'glass',
                'wood',
                'wood',
                'wood',
            ],
            preparationCost: 2,
            slots: 3,
            level: 2,
            yields: { fame: 3, coins: 3, shards: 1 },
        },
        T21_BalsamosSkull: {
            category: 'spiritual',
            name: "Balsamo's Skull",
            componentRequirements: ['padlock', 'rope', 'rope', 'metal', 'metal', 'metal'],
            preparationCost: 2,
            slots: 3,
            level: 3,
            yields: { fame: 4, coins: 3, shards: 2 },
        },
        T22_Séance: {
            category: 'spiritual',
            name: 'S\u00e9ance',
            componentRequirements: ['mirror', 'petroleum', 'petroleum', 'glass', 'glass', 'wood', 'wood', 'wood'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 7, coins: 5, shards: 1 },
        },
        T23_SkeletonDance: {
            category: 'spiritual',
            name: 'Skeleton Dance',
            componentRequirements: ['cog', 'cog', 'rope', 'rope', 'glass', 'glass', 'glass'],
            preparationCost: 3,
            slots: 3,
            level: 3,
            yields: { fame: 6, coins: 4, shards: 0 },
        },
        T24_Metamorphosis: {
            category: 'spiritual',
            name: 'Metamorphosis',
            componentRequirements: [
                'disguise',
                'disguise',
                'disguise',
                'rope',
                'rope',
                'rope',
                'fabric',
                'fabric',
                'fabric',
                'glass',
                'glass',
                'glass',
            ],
            preparationCost: 3,
            slots: 3,
            level: 3,
            yields: { fame: 10, coins: 4, shards: 0 },
        },
        T25_BarricadedBarrels: {
            category: 'escape',
            name: 'Barricaded Barrels',
            componentRequirements: ['wood', 'wood'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 1, coins: 1, shards: 0 },
        },
        T26_StocksEscape: {
            category: 'escape',
            name: 'Stocks Escape',
            componentRequirements: ['wood', 'wood', 'metal', 'metal'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 0, coins: 1, shards: 1 },
        },
        T27_BurningMummy: {
            category: 'escape',
            name: 'Burning Mummy',
            componentRequirements: ['petroleum', 'fabric', 'fabric', 'fabric'],
            preparationCost: 1,
            slots: 1,
            level: 1,
            yields: { fame: 2, coins: 2, shards: 0 },
        },
        T28_WaterTankEscape: {
            category: 'escape',
            name: 'Water Tank Escape',
            componentRequirements: ['rope', 'glass', 'glass', 'metal', 'metal'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 1, coins: 2, shards: 1 },
        },
        T29_PrisonBreak: {
            category: 'escape',
            name: 'Prison Break',
            componentRequirements: ['disguise', 'disguise', 'metal', 'metal', 'metal'],
            preparationCost: 1,
            slots: 2,
            level: 2,
            yields: { fame: 3, coins: 3, shards: 0 },
        },
        T30_ZigZagLady: {
            category: 'escape',
            name: 'Zig Zag Lady',
            componentRequirements: ['petroleum', 'fabric', 'wood', 'wood', 'wood'],
            preparationCost: 1,
            slots: 3,
            level: 2,
            yields: { fame: 2, coins: 3, shards: 0 },
        },
        T31_Walled: {
            category: 'escape',
            name: 'Walled',
            componentRequirements: ['padlock', 'wood', 'wood', 'wood', 'metal', 'metal', 'metal'],
            preparationCost: 1,
            slots: 2,
            level: 2,
            yields: { fame: 3, coins: 2, shards: 1 },
        },
        T32_WolfCage: {
            category: 'escape',
            name: 'Wolf Cage',
            componentRequirements: ['petroleum', 'animal', 'animal', 'metal', 'metal'],
            preparationCost: 1,
            slots: 1,
            level: 2,
            yields: { fame: 3, coins: 3, shards: 1 },
        },
        T33_BuriedAlive: {
            category: 'escape',
            name: 'Buried Alive',
            componentRequirements: ['padlock', 'padlock', 'padlock', 'wood', 'wood', 'wood'],
            preparationCost: 1,
            slots: 2,
            level: 3,
            yields: { fame: 4, coins: 4, shards: 0 },
        },
        T34_AssistantsRevenge: {
            category: 'escape',
            name: "Assistant's Revenge",
            componentRequirements: ['mirror', 'mirror', 'saw', 'saw', 'glass', 'glass', 'glass'],
            preparationCost: 1,
            slots: 1,
            level: 3,
            yields: { fame: 6, coins: 6, shards: 0 },
        },
        T35_IronMaiden: {
            category: 'escape',
            name: 'Iron Maiden',
            componentRequirements: ['padlock', 'padlock', 'saw', 'saw', 'saw', 'metal', 'metal', 'metal'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 5, coins: 5, shards: 1 },
        },
        T36_TransportedMan: {
            category: 'escape',
            name: 'Transported Man',
            componentRequirements: ['disguise', 'disguise', 'petroleum', 'petroleum', 'fabric', 'fabric', 'fabric'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 5, coins: 3, shards: 2 },
        },
        T37_LinkingRings: {
            category: 'mechanical',
            name: 'Linking Rings',
            componentRequirements: ['metal', 'metal'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 0, coins: 2, shards: 0 },
        },
        T38_LivingPiano: {
            category: 'mechanical',
            name: 'Living Piano',
            componentRequirements: ['animal', 'glass', 'wood'],
            preparationCost: 1,
            slots: 3,
            level: 1,
            yields: { fame: 1, coins: 1, shards: 0 },
        },
        T39_ChineseSticks: {
            category: 'mechanical',
            name: 'Chinese Sticks',
            componentRequirements: ['rope', 'rope', 'wood', 'wood'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 1, coins: 2, shards: 0 },
        },
        T40_Levitation: {
            category: 'mechanical',
            name: 'Levitation',
            componentRequirements: ['rope', 'petroleum', 'petroleum', 'glass', 'glass', 'glass'],
            preparationCost: 1,
            slots: 2,
            level: 1,
            yields: { fame: 2, coins: 3, shards: 0 },
        },
        T41_MechanicalHornet: {
            category: 'mechanical',
            name: 'Mechanical Hornet',
            componentRequirements: ['cog', 'petroleum', 'metal', 'metal', 'metal'],
            preparationCost: 2,
            slots: 2,
            level: 2,
            yields: { fame: 4, coins: 3, shards: 0 },
        },
        T42_SawingTheAssistantInHalf: {
            category: 'mechanical',
            name: 'Sawing the Assistant in Half',
            componentRequirements: ['saw', 'saw', 'saw', 'wood', 'wood', 'wood'],
            preparationCost: 1,
            slots: 3,
            level: 2,
            yields: { fame: 1, coins: 5, shards: 0 },
        },
        T43_VanishingBirdCage: {
            category: 'mechanical',
            name: 'Vanishing Bird Cage',
            componentRequirements: ['cog', 'animal', 'animal', 'fabric', 'fabric'],
            preparationCost: 1,
            slots: 2,
            level: 2,
            yields: { fame: 2, coins: 3, shards: 1 },
        },
        T44_BulletCatch: {
            category: 'mechanical',
            name: 'Bullet Catch',
            componentRequirements: ['petroleum', 'petroleum', 'rope', 'rope', 'metal', 'metal'],
            preparationCost: 2,
            slots: 3,
            level: 2,
            yields: { fame: 3, coins: 4, shards: 0 },
        },
        T45_AztecLady: {
            category: 'mechanical',
            name: 'Aztec Lady',
            componentRequirements: ['padlock', 'cog', 'cog', 'saw', 'glass', 'glass'],
            preparationCost: 2,
            slots: 3,
            level: 3,
            yields: { fame: 5, coins: 5, shards: 0 },
        },
        T46_HorrorSaws: {
            category: 'mechanical',
            name: 'Horror Saws',
            componentRequirements: ['cog', 'cog', 'saw', 'saw', 'wood', 'wood', 'wood'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 4, coins: 8, shards: 0 },
        },
        T47_Automaton: {
            category: 'mechanical',
            name: 'Automaton',
            componentRequirements: ['cog', 'cog', 'cog', 'petroleum', 'petroleum', 'petroleum', 'metal', 'metal', 'metal'],
            preparationCost: 1,
            slots: 1,
            level: 3,
            yields: { fame: 7, coins: 7, shards: 0 },
        },
        T48_Hellhound: {
            category: 'mechanical',
            name: 'Hellhound',
            componentRequirements: ['padlock', 'padlock', 'petroleum', 'animal', 'animal', 'fabric', 'fabric', 'fabric'],
            preparationCost: 2,
            slots: 2,
            level: 3,
            yields: { fame: 6, coins: 5, shards: 1 },
        },
    },
    characters: {
        magician: { actionPoints: 3, name: 'Magician', specialist: false },
        apprentice: { actionPoints: 1, name: 'Apprentice', specialist: false },
        assistant: { actionPoints: 2, name: 'Assistant', specialist: true },
        manager: { actionPoints: 2, name: 'Manager', specialist: true },
        engineer: { actionPoints: 2, name: 'Engineer', specialist: true },
    },
    components: {
        wood: { cost: 1, name: 'wood' },
        glass: { cost: 1, name: 'glass' },
        metal: { cost: 1, name: 'metal' },
        fabric: { cost: 1, name: 'fabric' },
        rope: { cost: 2, name: 'rope' },
        petroleum: { cost: 2, name: 'petroleum' },
        saw: { cost: 2, name: 'saw' },
        animal: { cost: 2, name: 'animal' },
        padlock: { cost: 3, name: 'padlock' },
        mirror: { cost: 3, name: 'mirror' },
        disguise: { cost: 3, name: 'disguise' },
        cog: { cost: 3, name: 'cog' },
    },
};
