export const gamedatas = {
    players: {
        2322020: {
            id: 2322020,
            no: 1,
            name: 'Tisaac0',
            color: '60aaa1',
            eliminated: 0,
            score: 5,
            scoreAux: 0,
            zombie: 0,
            shards: 1,
            coins: 10,
            initiative: 1,
            colorName: 'blue',
            color_back: null,
            is_ai: '0',
            beginner: true,
            avatar: '000000',
            ack: 'ack',
        },
        2322021: {
            id: 2322021,
            no: 2,
            name: 'Tisaac1',
            color: 'cf4a1f',
            eliminated: 0,
            score: 5,
            scoreAux: 0,
            zombie: 0,
            shards: 1,
            coins: 12,
            initiative: 2,
            colorName: 'red',
            color_back: null,
            is_ai: '0',
            beginner: true,
            avatar: '000000',
            ack: 'ack',
        },
    },
    globals: {
        currentTurn: 1,
        dice: {
            money: ['not-available', 'not-available'],
            trick: ['not-available', 'not-available'],
            character: ['not-available', 'not-available'],
        },
        drawAssignmentCardsAction: {
            currentCost: 1,
        },
        locationActions: {
            locationId: null,
            oneTimeActionsUsed: [],
            remainingActionPoints: 0,
        },
        marketRow: {
            buyArea: ['wood', 'metal', 'glass', 'fabric'],
            orderArea: [],
            quickOrder: null,
        },
        pickingComponents: [],
        isDarkAlley: false,
        isBeginnersSetup: true,
    },
    tricks: {
        available: [
            {
                id: 1,
                type: 'T01_EnchantedButterflies',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 2,
                type: 'T02_RabbitFromTheTopHat',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 3,
                type: 'T03_PubInABottle',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 4,
                type: 'T04_CardManipulation',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 5,
                type: 'T05_SelfDecapitation',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 6,
                type: 'T06_PaperShred',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 7,
                type: 'T07_ShatteredMirror',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 8,
                type: 'T08_FishingInTheAir',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 13,
                type: 'T13_MindReading',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 14,
                type: 'T14_BreathOfLife',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 15,
                type: 'T15_SpiritHand',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 16,
                type: 'T16_WindowToTheOtherworld',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 17,
                type: 'T17_FloatingTable',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 18,
                type: 'T18_FutureSight',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 19,
                type: 'T19_PeppersGhost',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 20,
                type: 'T20_GhostTrap',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 25,
                type: 'T25_BarricadedBarrels',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 26,
                type: 'T26_StocksEscape',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 27,
                type: 'T27_BurningMummy',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 28,
                type: 'T28_WaterTankEscape',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 29,
                type: 'T29_PrisonBreak',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 30,
                type: 'T30_ZigZagLady',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 31,
                type: 'T31_Walled',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 32,
                type: 'T32_WolfCage',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 37,
                type: 'T37_LinkingRings',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 38,
                type: 'T38_LivingPiano',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 39,
                type: 'T39_ChineseSticks',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 40,
                type: 'T40_Levitation',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 41,
                type: 'T41_MechanicalHornet',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 42,
                type: 'T42_SawingTheAssistantInHalf',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 43,
                type: 'T43_VanishingBirdCage',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
            {
                id: 44,
                type: 'T44_BulletCatch',
                location: 'available',
                state: 0,
                playerId: null,
                suit: null,
            },
        ],
        player: {
            2322020: [],
            2322021: [],
        },
    },
    performances: {
        active: [
            {
                id: 11,
                type: 'P11_RiversideTheater',
                location: 'active',
                state: 1,
            },
        ],
        deck: [
            {
                state: -2,
                theater: 'riverside_theater',
            },
            {
                state: -1,
                theater: 'riverside_theater',
            },
            {
                state: -3,
                theater: 'grand_magorian',
            },
            {
                state: -4,
                theater: 'grand_magorian',
            },
        ],
    },
    assignments: {
        hand: [
            {
                id: 1,
                type: 'A01_Theater',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 2,
                type: 'A01_Theater',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 3,
                type: 'A01_Theater',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 7,
                type: 'A02_Downtown',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 8,
                type: 'A02_Downtown',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 11,
                type: 'A03_MarketRow',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 12,
                type: 'A03_MarketRow',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 15,
                type: 'A04_Workshop',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
            {
                id: 16,
                type: 'A04_Workshop',
                location: 'hand',
                state: 0,
                playerId: 2322020,
            },
        ],
        deckRemaining: {
            downtown_deck: 10,
            workshop_deck: 10,
            market_row_deck: 10,
            theater_deck: 10,
        },
        discards: {
            downtown_discard: [],
            workshop_discard: [],
            market_row_discard: [],
            theater_discard: [],
        },
        assigned: {
            my: [],
            other: {
                2322021: {
                    revealed: [],
                    hidden: [],
                },
            },
        },
    },
    prophecies: {
        pending: [],
        active: [],
        deckRemaining: 0,
        discarded: [],
    },
    magicians: {
        available: [
            {
                id: 1,
                type: 'M01_MasterOfChains',
                location: 'available',
                state: 0,
                playerId: null,
            },
            {
                id: 2,
                type: 'M02_TheGreatOptico',
                location: 'available',
                state: 0,
                playerId: null,
            },
            {
                id: 3,
                type: 'M03_PriestessOfMysticism',
                location: 'available',
                state: 0,
                playerId: null,
            },
            {
                id: 4,
                type: 'M04_TheMechaniker',
                location: 'available',
                state: 0,
                playerId: null,
            },
            {
                id: 5,
                type: 'M05_TheRedLotus',
                location: 'available',
                state: 0,
                playerId: null,
            },
            {
                id: 6,
                type: 'M06_TheGentleman',
                location: 'available',
                state: 0,
                playerId: null,
            },
            {
                id: 7,
                type: 'M07_YorubaSpiritmaster',
                location: 'available',
                state: 0,
                playerId: null,
            },
            {
                id: 8,
                type: 'M08_Electra',
                location: 'available',
                state: 0,
                playerId: null,
            },
        ],
        player: {
            2322020: null,
            2322021: null,
        },
    },
    trickMarkers: {
        available: [
            {
                id: 1,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 2,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 3,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 4,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 5,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 6,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 7,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 8,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 9,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 10,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 11,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 12,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 13,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 14,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 15,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 16,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322020,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 17,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 18,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 19,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 20,
                location: 'available',
                state: 0,
                suit: 'spades',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 21,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 22,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 23,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 24,
                location: 'available',
                state: 0,
                suit: 'hearts',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 25,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 26,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 27,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 28,
                location: 'available',
                state: 0,
                suit: 'diamonds',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 29,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 30,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 31,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
            {
                id: 32,
                location: 'available',
                state: 0,
                suit: 'clubs',
                playerId: 2322021,
                trickId: null,
                slotId: null,
                topTrickCategory: null,
            },
        ],
        prepared: [],
        scheduled: [],
    },
    characters: {
        supply: [
            {
                id: 2,
                location: 'supply',
                state: 0,
                playerId: 2322020,
                type: 'engineer',
                onAssistantBoard: false,
            },
            {
                id: 3,
                location: 'supply',
                state: 0,
                playerId: 2322020,
                type: 'manager',
                onAssistantBoard: false,
            },
            {
                id: 4,
                location: 'supply',
                state: 0,
                playerId: 2322020,
                type: 'assistant',
                onAssistantBoard: false,
            },
            {
                id: 6,
                location: 'supply',
                state: 0,
                playerId: 2322020,
                type: 'apprentice',
                onAssistantBoard: false,
            },
            {
                id: 7,
                location: 'supply',
                state: 0,
                playerId: 2322020,
                type: 'apprentice',
                onAssistantBoard: false,
            },
            {
                id: 8,
                location: 'supply',
                state: 0,
                playerId: 2322020,
                type: 'apprentice',
                onAssistantBoard: false,
            },
            {
                id: 10,
                location: 'supply',
                state: 0,
                playerId: 2322021,
                type: 'engineer',
                onAssistantBoard: false,
            },
            {
                id: 11,
                location: 'supply',
                state: 0,
                playerId: 2322021,
                type: 'manager',
                onAssistantBoard: false,
            },
            {
                id: 12,
                location: 'supply',
                state: 0,
                playerId: 2322021,
                type: 'assistant',
                onAssistantBoard: false,
            },
            {
                id: 14,
                location: 'supply',
                state: 0,
                playerId: 2322021,
                type: 'apprentice',
                onAssistantBoard: false,
            },
            {
                id: 15,
                location: 'supply',
                state: 0,
                playerId: 2322021,
                type: 'apprentice',
                onAssistantBoard: false,
            },
            {
                id: 16,
                location: 'supply',
                state: 0,
                playerId: 2322021,
                type: 'apprentice',
                onAssistantBoard: false,
            },
        ],
        board: [],
        idle: [
            {
                id: 1,
                location: 'idle-player-board',
                state: 0,
                playerId: 2322020,
                type: 'magician',
                onAssistantBoard: false,
            },
            {
                id: 5,
                location: 'idle-player-board',
                state: 0,
                playerId: 2322020,
                type: 'apprentice',
                onAssistantBoard: false,
            },
            {
                id: 9,
                location: 'idle-player-board',
                state: 0,
                playerId: 2322021,
                type: 'magician',
                onAssistantBoard: false,
            },
            {
                id: 13,
                location: 'idle-player-board',
                state: 0,
                playerId: 2322021,
                type: 'apprentice',
                onAssistantBoard: false,
            },
        ],
        hiredSpecialists: {
            2322020: [],
            2322021: [],
        },
    },
    components: {
        player: {
            2322020: [
                {
                    id: 1,
                    type: 'wood',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 2,
                    type: 'glass',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 3,
                    type: 'metal',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 4,
                    type: 'fabric',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 5,
                    type: 'rope',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 6,
                    type: 'petroleum',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 7,
                    type: 'saw',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 8,
                    type: 'animal',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 9,
                    type: 'paddlock',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 10,
                    type: 'mirror',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 11,
                    type: 'disguise',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
                {
                    id: 12,
                    type: 'cog',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322020,
                    count: 0,
                },
            ],
            2322021: [
                {
                    id: 13,
                    type: 'wood',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 14,
                    type: 'glass',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 15,
                    type: 'metal',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 16,
                    type: 'fabric',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 17,
                    type: 'rope',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 18,
                    type: 'petroleum',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 19,
                    type: 'saw',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 20,
                    type: 'animal',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 21,
                    type: 'paddlock',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 22,
                    type: 'mirror',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 23,
                    type: 'disguise',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
                {
                    id: 24,
                    type: 'cog',
                    location: 'player-board',
                    state: 0,
                    playerId: 2322021,
                    count: 0,
                },
            ],
        },
    },
    posters: {
        all: {
            1: {
                id: 1,
                location: 'supply',
                state: 0,
                playerId: 2322020,
            },
            2: {
                id: 2,
                location: 'supply',
                state: 0,
                playerId: 2322021,
            },
        },
    },
    gamestate: {
        id: 805,
        active_player: '2322020',
        args: {
            optionalAction: false,
            anytimeActions: [
                {
                    description: 'Discard components',
                    id: 'Bga\\Games\\trickerionlegendsofillusion\\States\\Actions\\Anytime\\DiscardComponents',
                },
                {
                    description: 'Discard trick',
                    id: 'Bga\\Games\\trickerionlegendsofillusion\\States\\Actions\\Anytime\\DiscardTrick',
                },
            ],
            previousEngineChoices: 0,
            previousSteps: [],
            automaticAction: false,
            availableMagicians: [
                {
                    id: 1,
                    type: 'M01_MasterOfChains',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
                {
                    id: 2,
                    type: 'M02_TheGreatOptico',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
                {
                    id: 3,
                    type: 'M03_PriestessOfMysticism',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
                {
                    id: 4,
                    type: 'M04_TheMechaniker',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
                {
                    id: 5,
                    type: 'M05_TheRedLotus',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
                {
                    id: 6,
                    type: 'M06_TheGentleman',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
                {
                    id: 7,
                    type: 'M07_YorubaSpiritmaster',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
                {
                    id: 8,
                    type: 'M08_Electra',
                    location: 'available',
                    state: 0,
                    playerId: null,
                },
            ],
        },
        reflexion: {
            total: {
                2322020: 7767986,
                2322021: '7776000',
            },
            initial: {
                2322020: 7768344,
            },
            initial_ts: {
                2322020: 1774950658492,
            },
        },
        updateGameProgression: 0,
        name: 'ChooseMagician',
        type: 'activeplayer',
        description: '${actplayer} must choose a magician',
        descriptionmyturn: '${you} must choose a magician',
        action: null,
        possibleactions: ['actChooseMagician', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
        transitions: [],
        initialprivate: null,
    },
    tablespeed: '20',
    game_result_neutralized: '0',
    neutralized_player_id: '0',
    playerorder: [2322020, 2322021],
    gamestates: {
        1: {
            name: 'gameSetup',
            type: 'manager',
            description: 'Game setup',
            descriptionmyturn: '',
            action: 'stGameSetup',
            args: null,
            possibleactions: null,
            transitions: {
                '': 2,
            },
            updateGameProgression: false,
            initialprivate: null,
        },
        10: {
            name: 'TurnPreparation',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        40: {
            name: 'StartAssignment',
            type: 'multipleactiveplayer',
            description: 'Other players must assign their characters',
            descriptionmyturn: '${you} must assign your characters',
            action: null,
            args: null,
            possibleactions: ['actChangeAssignment'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: 50,
        },
        50: {
            name: 'AssignCharacters',
            type: 'private',
            description: '',
            descriptionmyturn: '${you} must assign your characters',
            action: null,
            args: null,
            possibleactions: ['actAssignCharacter', 'actAssignCharacters', 'actDone', 'actReset'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        60: {
            name: 'PlaceCharacters',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        70: {
            name: 'PerformancePhase',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        80: {
            name: 'EndTurnPhase',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        99: {
            name: 'gameEnd',
            type: 'manager',
            description: 'End of game',
            descriptionmyturn: '',
            action: 'stGameEnd',
            args: 'argGameEnd',
            possibleactions: null,
            transitions: null,
            updateGameProgression: false,
            initialprivate: null,
        },
        100: {
            name: 'Advertise',
            type: 'activeplayer',
            description: '${actplayer} must decide whether to advertise for ${cost} coins',
            descriptionmyturn: '${you} must decide whether to advertise for ${cost} coins',
            action: null,
            args: null,
            possibleactions: ['actAdvertise', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        120: {
            name: 'PlaceCharacter',
            type: 'activeplayer',
            description: '${actplayer} must place a character',
            descriptionmyturn: '${you} must place a character',
            action: null,
            args: null,
            possibleactions: [
                'actPlace',
                'actLeaveIdle',
                'actRestart',
                'actUndoToStep',
                'actPassOptionalAction',
                'actAnytimeAction',
            ],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        125: {
            name: 'PlayLocationAction',
            type: 'activeplayer',
            description: '${actplayer} must play location actions (remaining AP: ${remainingAps})',
            descriptionmyturn: '${you} must play location actions (remaining AP: ${remainingAps})',
            action: null,
            args: null,
            possibleactions: ['actPlayAction', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        200: {
            name: 'PickComponents',
            type: 'activeplayer',
            description:
                '${actplayer} must pick components to put in ${location} with a total value of ${totalValue} (remaining: ${remainingValue})',
            descriptionmyturn:
                '${you} must pick components to put in ${location} with a total value of ${totalValue} (remaining: ${remainingValue})',
            action: null,
            args: null,
            possibleactions: [
                'actPickComponent',
                'actDone',
                'actRestart',
                'actUndoToStep',
                'actPassOptionalAction',
                'actAnytimeAction',
            ],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        205: {
            name: 'LearnTrick',
            type: 'activeplayer',
            description: '${actplayer} must learn a trick',
            descriptionmyturn: '${you} must learn a trick',
            action: null,
            args: null,
            possibleactions: ['actLearnTrick', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        210: {
            name: 'HireCharacter',
            type: 'activeplayer',
            description: '${actplayer} must hire a character',
            descriptionmyturn: '${you} must hire a character',
            action: null,
            args: null,
            possibleactions: ['actHireCharacter', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        211: {
            name: 'HiredCharacterSetup',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: ['actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        215: {
            name: 'PrepareTrick',
            type: 'activeplayer',
            description: '${actplayer} must prepare a trick',
            descriptionmyturn: '${you} must prepare a trick',
            action: null,
            args: null,
            possibleactions: ['actPrepareTrick', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        220: {
            name: 'DrawAssignmentCards',
            type: 'activeplayer',
            description: '${actplayer} must draw assignment cards',
            descriptionmyturn: '${you} must draw assignment cards',
            action: null,
            args: null,
            possibleactions: [
                'actDrawAssignmentCards',
                'actDiscardCards',
                'actRestart',
                'actUndoToStep',
                'actPassOptionalAction',
                'actAnytimeAction',
            ],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        225: {
            name: 'EnhanceCharacter',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: ['actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        230: {
            name: 'FortuneTelling',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: ['actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        235: {
            name: 'MakeDieUnavailable',
            type: 'activeplayer',
            description: '${actplayer} must choose which die to turn to "X"',
            descriptionmyturn: '${you} must choose which die to turn to "X"',
            action: null,
            args: null,
            possibleactions: [
                'actMakeDieUnavailable',
                'actRestart',
                'actUndoToStep',
                'actPassOptionalAction',
                'actAnytimeAction',
            ],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        240: {
            name: 'TakeCoins',
            type: 'activeplayer',
            description: '${actplayer} must take coins',
            descriptionmyturn: '${you} must take coins',
            action: null,
            args: null,
            possibleactions: ['actTakeCoins', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        245: {
            name: 'RerollDie',
            type: 'activeplayer',
            description: '${actplayer} must reroll a die',
            descriptionmyturn: '${you} must reroll a die',
            action: null,
            args: null,
            possibleactions: ['actRerollDie', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        250: {
            name: 'SetDie',
            type: 'activeplayer',
            description: '${actplayer} must set a die',
            descriptionmyturn: '${you} must set a die',
            action: null,
            args: null,
            possibleactions: ['actSetDie', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        255: {
            name: 'BuyComponents',
            type: 'activeplayer',
            description: '${actplayer} must buy components',
            descriptionmyturn: '${you} must buy components',
            action: null,
            args: null,
            possibleactions: ['actBuyComponents', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        260: {
            name: 'OrderComponent',
            type: 'activeplayer',
            description: '${actplayer} must order components',
            descriptionmyturn: '${you} must order components',
            action: null,
            args: null,
            possibleactions: ['actOrderComponents', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        265: {
            name: 'QuickOrderComponent',
            type: 'activeplayer',
            description: '${actplayer} must quick order components',
            descriptionmyturn: '${you} must quick order components',
            action: null,
            args: null,
            possibleactions: [
                'actQuickOrderComponents',
                'actRestart',
                'actUndoToStep',
                'actPassOptionalAction',
                'actAnytimeAction',
            ],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        270: {
            name: 'MoveComponents',
            type: 'activeplayer',
            description: '${actplayer} must decide which components to move',
            descriptionmyturn: '${you} must decide which components to move',
            action: null,
            args: null,
            possibleactions: ['actMoveComponent', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        275: {
            name: 'MoveTrick',
            type: 'activeplayer',
            description: '${actplayer} must decide which trick to move',
            descriptionmyturn: '${you} must decide which trick to move',
            action: null,
            args: null,
            possibleactions: ['actMoveTrick', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        280: {
            name: 'MoveApprentice',
            type: 'activeplayer',
            description: '${actplayer} must decide which apprentice to move',
            descriptionmyturn: '${you} must decide which apprentice to move',
            action: null,
            args: null,
            possibleactions: ['actMoveApprentice', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        285: {
            name: 'SetupTrick',
            type: 'activeplayer',
            description: '${actplayer} must setup a trick',
            descriptionmyturn: '${you} must setup a trick',
            action: null,
            args: null,
            possibleactions: ['actSetupTrick', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        290: {
            name: 'Reschedule',
            type: 'activeplayer',
            description: '${actplayer} must reschedule a trick',
            descriptionmyturn: '${you} must reschedule a trick',
            action: null,
            args: null,
            possibleactions: ['actRescheduleTrick', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        295: {
            name: 'GetShards',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: ['actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        300: {
            name: 'GetCoins',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: ['actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        305: {
            name: 'GetFame',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: ['actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        600: {
            name: 'Performance',
            type: 'activeplayer',
            description: '${actplayer} must choose a performance to perform for ${day}',
            descriptionmyturn: '${you} must choose a performance to perform for ${day}',
            action: null,
            args: null,
            possibleactions: ['actSelectPerformance', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        700: {
            name: 'DiscardComponents',
            type: 'activeplayer',
            description: '${actplayer} must decide which components to discard',
            descriptionmyturn: '${you} must decide which components to discard',
            action: null,
            args: null,
            possibleactions: ['actDiscardComponent', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        705: {
            name: 'DiscardTrick',
            type: 'activeplayer',
            description: '${actplayer} must decide which trick to discard',
            descriptionmyturn: '${you} must decide which trick to discard',
            action: null,
            args: null,
            possibleactions: ['actDiscardTrick', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        805: {
            name: 'ChooseMagician',
            type: 'activeplayer',
            description: '${actplayer} must choose a magician',
            descriptionmyturn: '${you} must choose a magician',
            action: null,
            possibleactions: ['actChooseMagician', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            initialprivate: null,
        },
        810: {
            name: 'SetupTurn',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        820: {
            name: 'FinishEngineerSetup',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        830: {
            name: 'FinishSetup',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        901: {
            name: 'ResolveChoice',
            type: 'activeplayer',
            description: '${actplayer} must choose which effect to resolve',
            descriptionmyturn: '${you} must choose which effect to resolve',
            action: null,
            args: null,
            possibleactions: ['actChooseAction', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        903: {
            name: 'ConfirmTurn',
            type: 'activeplayer',
            description: '${actplayer} must finalize their decisions.',
            descriptionmyturn: "${you} must finalize your decisions. When you do you won't be able to undo past this point",
            action: null,
            args: null,
            possibleactions: ['actConfirmTurn', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        904: {
            name: 'ConfirmPartialTurn',
            type: 'activeplayer',
            description: '${actplayer} must confirm switch to ${player_name}',
            descriptionmyturn: '${you} must confirm switch to ${player_name}',
            action: null,
            args: null,
            possibleactions: ['actConfirmTurn', 'actRestart', 'actUndoToStep', 'actPassOptionalAction', 'actAnytimeAction'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        907: {
            name: 'GenericGameState',
            type: 'game',
            description: '',
            descriptionmyturn: '',
            action: null,
            args: null,
            possibleactions: [],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
        999: {
            name: 'DummyEnd',
            type: 'multipleactiveplayer',
            description: 'Please report any possible end of the game bugs and click finish to end the game',
            descriptionmyturn: 'Please report any possible end of the game bugs and click finish to end the game',
            action: null,
            args: null,
            possibleactions: ['actEnd'],
            transitions: [],
            updateGameProgression: false,
            initialprivate: null,
        },
    },
    notifications: {
        last_packet_id: '1',
        move_nbr: '1',
    },
    decision: {
        decision_type: 'none',
    },
};
